name: Tests

on:
  push:
    branches:
      - main   

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: replace
    
    
      - uses: actions/checkout@v3

      - name: Install poetry & dependencies
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'poetry'
      - run: poetry install
      
      - name: Run tests
        run: poetry run pytest
